#!/usr/bin/env python3
from argparse import ArgumentParser
from subprocess import check_call
from pathlib import Path
import os

import render


def main():
    p = ArgumentParser()
    render.setup_parser(p)
    p.add_argument('--area', required=True)
    p.add_argument('--postcode', required=True)
    args = p.parse_args()

    jpath = Path(args.json)
    if jpath.exists():
        jpath.rename(str(jpath) + '.old') # to prevent scraper from appending

    cmd = [
        'scrapy', 'crawl', 'deliveroo_spider',
        '-o', str(jpath),
        '-s', 'LOG_LEVEL=INFO',
        '-s', 'BASE_URL=' + args.base_url,
        '-s', 'POSTCODE=' + args.postcode,
        '-s', 'AREA=' + args.area
    ]
    print("scraping: " + ' '.join(cmd))
    check_call(cmd, cwd=Path(__file__).parent)

    print("rendering...")
    render.run(args)


if __name__ == '__main__':
    main()
