#!/usr/bin/env python3
from pathlib import Path
import sys
from subprocess import check_call
import time

def run(args) -> None:
    cli: Path   = args.cli
    index: Path = args.index
    while True:
        try:
            check_call([
                str(cli),
                'serve',
                '--index', str(index)
            ])
        except BaseException as e:
            # it never crashed before, but would be awkward if it does do it live!
            print("whoops! something went wrong!", file=sys.stderr)
            print(str(e), file=sys.stderr)

        time.sleep(3)


def main():
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('--index', type=Path, default='./scrapyroo-index')
    p.add_argument('--cli', type=Path, default='./tantivy-cli/bin/tantivy')
    args = p.parse_args()
    run(args)


if __name__ == '__main__':
    main()
